MOTOR_CHANNEL = ['CFC5', 'CFC6', 'CFC3', 'CFC4', 'Cz,', 'CCP5', 'CCP6', 'CCP3', 'CCP4']
PARIENTAL_CHANNEL = ['Pz', 'P3', 'P4', 'P7', 'P8']
FRONTAL_CHANNEL = ['F7', 'FAF5', 'F3', 'AFp1', 'FAF1', 'AFp2', 'FAF2', 'FAF6', 'F4', 'F8']
OCCIPITAL_CHANNEL = ['PPO1', 'OPO1', 'OPO2', 'PPO2']

MAXIMUM_NUMBER_OF_PROCESSES=15